### ISSUE TITLE
presumably you have seen the gamekit random distribution models? I think you've exceeded Apple here. 

### ISSUE THREAD

**Issue by johndpope** [qiter/swift_astarPath#1]
one problem I'm seeing here - any ideas?

![screen shot 2015-11-05 at 11 31 28 pm](https://cloud.githubusercontent.com/assets/289994/10968453/6384b172-8415-11e5-9d5c-07b5afc4a971.png)

**Comment by johndpope** [comment]
https://github.com/SebastianOsinski/SORandom

**Comment by qiter** [comment]
Thx.
This project is test demo.  Using swift1.0.
That's problem is random function.
If you run this project is error,you have to replace this random function randDiscUniform().Will be running.
I will change this random  function.

**Comment by qiter** [comment]
randDiscUniform() function is  in the GridViewController.swift  files.
